site_name: Jo3 Cluster Documentation
site_url: https://jzacharie.github.io/jo3-docs/
repo_url: https://github.com/JZacharie/jo3-docs
repo_name: JZacharie/jo3-docs
edit_uri: ""

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Infrastructure:
      - Nodes: infrastructure/nodes.md
      - Storage: infrastructure/storage.md
  - Applications:
      - AI:
          - Overview: applications/ai.md
          - chromadb: applications/ai/chromadb.md
          - docling: applications/ai/docling.md
          - f5-tts: applications/ai/f5-tts.md
          - facefusion: applications/ai/facefusion.md
          - gpu-hot: applications/ai/gpu-hot.md
          - k8sgpt: applications/ai/k8sgpt.md
          - libre-chat: applications/ai/libre-chat.md
          - lobe-chat: applications/ai/lobe-chat.md
          - nv-manager: applications/ai/nv-manager.md
          - ollama: applications/ai/ollama.md
          - open-webui: applications/ai/open-webui.md
          - openai-whisper-asr-webservice: applications/ai/openai-whisper-asr-webservice.md
          - whisperx: applications/ai/whisperx.md
      - Dev Tools:
          - awx: applications/dev-tools/awx.md
          - awx-operator: applications/dev-tools/awx-operator.md
          - cloudbeaver: applications/dev-tools/cloudbeaver.md
          - code-server: applications/dev-tools/code-server.md
          - cyberchef: applications/dev-tools/cyberchef.md
          - excalidraw: applications/dev-tools/excalidraw.md
          - gotenberg: applications/dev-tools/gotenberg.md
          - it-tools: applications/dev-tools/it-tools.md
          - permission-manager: applications/dev-tools/permission-manager.md
          - persistence-defectdojo: applications/dev-tools/persistence-defectdojo.md
          - pgadmin4: applications/dev-tools/pgadmin4.md
          - renovate: applications/dev-tools/renovate.md
          - swaggerui: applications/dev-tools/swaggerui.md
          - wh2pg: applications/dev-tools/wh2pg.md
          - zap-advanced: applications/dev-tools/zap-advanced.md
      - Home:
          - emqx: applications/home/emqx.md
          - home-assistant: applications/home/home-assistant.md
          - meteo: applications/home/meteo.md
      - Infrastructure:
          - appflowy-sbx: applications/infrastructure/appflowy-sbx.md
          - argo-events: applications/infrastructure/argo-events.md
          - argo-rollouts: applications/infrastructure/argo-rollouts.md
          - argo-workflows: applications/infrastructure/argo-workflows.md
          - argocd-extras: applications/infrastructure/argocd-extras.md
          - argocd-notifications: applications/infrastructure/argocd-notifications.md
          - blinko: applications/infrastructure/blinko.md
          - browserless-chrome: applications/infrastructure/browserless-chrome.md
          - chartdb: applications/infrastructure/chartdb.md
          - chatterbox: applications/infrastructure/chatterbox.md
          - cilium: applications/infrastructure/cilium.md
          - cloudnative-pg: applications/infrastructure/cloudnative-pg.md
          - cups: applications/infrastructure/cups.md
          - demo-rum: applications/infrastructure/demo-rum.md
          - descheduler: applications/infrastructure/descheduler.md
          - devdocs: applications/infrastructure/devdocs.md
          - error-pages: applications/infrastructure/error-pages.md
          - fission: applications/infrastructure/fission.md
          - fluent-bit: applications/infrastructure/fluent-bit.md
          - fluent-bit-sbx: applications/infrastructure/fluent-bit-sbx.md
          - google-mcp: applications/infrastructure/google-mcp.md
          - guacamole sbx: applications/infrastructure/guacamole sbx.md
          - homepage: applications/infrastructure/homepage.md
          - ironcalc: applications/infrastructure/ironcalc.md
          - karakeep: applications/infrastructure/karakeep.md
          - keda: applications/infrastructure/keda.md
          - keda-http-addon: applications/infrastructure/keda-http-addon.md
          - keydb: applications/infrastructure/keydb.md
          - knative-operator: applications/infrastructure/knative-operator.md
          - kube-ops-view: applications/infrastructure/kube-ops-view.md
          - kubernetes-mcp: applications/infrastructure/kubernetes-mcp.md
          - local-path: applications/infrastructure/local-path.md
          - mariadb-operator: applications/infrastructure/mariadb-operator.md
          - mariadb-operator-crd: applications/infrastructure/mariadb-operator-crd.md
          - metabase: applications/infrastructure/metabase.md
          - n8n: applications/infrastructure/n8n.md
          - n8n-dev: applications/infrastructure/n8n-dev.md
          - nack: applications/infrastructure/nack.md
          - nats: applications/infrastructure/nats.md
          - netbox: applications/infrastructure/netbox.md
          - nmap: applications/infrastructure/nmap.md
          - node-red: applications/infrastructure/node-red.md
          - ntfy: applications/infrastructure/ntfy.md
          - o2-openobserve-import-dashboards: applications/infrastructure/o2-openobserve-import-dashboards.md
          - o2c: applications/infrastructure/o2c.md
          - otel-collector-argocd: applications/infrastructure/otel-collector-argocd.md
          - otel-collector-gpu: applications/infrastructure/otel-collector-gpu.md
          - rabbitmq: applications/infrastructure/rabbitmq.md
          - redis: applications/infrastructure/redis.md
          - redis-n: applications/infrastructure/redis-n.md
          - redis-s: applications/infrastructure/redis-s.md
          - rsshub: applications/infrastructure/rsshub.md
          - scriberr: applications/infrastructure/scriberr.md
          - sim: applications/infrastructure/sim.md
          - tika: applications/infrastructure/tika.md
          - traefik: applications/infrastructure/traefik.md
          - vault-unseal: applications/infrastructure/vault-unseal.md
          - velld: applications/infrastructure/velld.md
          - velld-app: applications/infrastructure/velld-app.md
          - whoami: applications/infrastructure/whoami.md
      - Media:
          - Overview: applications/media.md
          - audiobookshelf: applications/media/audiobookshelf.md
          - calibre: applications/media/calibre.md
          - deemix: applications/media/deemix.md
          - handbrake: applications/media/handbrake.md
          - immich: applications/media/immich.md
          - jellyfin-prd: applications/media/jellyfin-prd.md
          - photoprism: applications/media/photoprism.md
          - photos: applications/media/photos.md
          - qbittorrent: applications/media/qbittorrent.md
          - restreamer: applications/media/restreamer.md
          - youtubedl: applications/media/youtubedl.md
      - Observability:
          - Overview: applications/observability.md
          - gaps: applications/observability/gaps.md
          - gatus: applications/observability/gatus.md
          - grafana: applications/observability/grafana.md
          - influxdb2: applications/observability/influxdb2.md
          - kube-prometheus-stack: applications/observability/kube-prometheus-stack.md
          - mimir-distributed: applications/observability/mimir-distributed.md
          - o2-openobserve: applications/observability/o2-openobserve.md
          - opentelemetry-operator: applications/observability/opentelemetry-operator.md
          - prometheus-blackbox-exporter: applications/observability/prometheus-blackbox-exporter.md
          - steampipe-powerpipe-manifests: applications/observability/steampipe-powerpipe-manifests.md
          - watchyourlan: applications/observability/watchyourlan.md
      - Productivity:
          - Overview: applications/productivity.md
          - actualbudget: applications/productivity/actualbudget.md
          - changedetection-io: applications/productivity/changedetection-io.md
          - convertx: applications/productivity/convertx.md
          - docspell: applications/productivity/docspell.md
          - docuseal: applications/productivity/docuseal.md
          - freshrss: applications/productivity/freshrss.md
          - ihatemoney: applications/productivity/ihatemoney.md
          - karma: applications/productivity/karma.md
          - language-tool: applications/productivity/language-tool.md
          - littlelink-server: applications/productivity/littlelink-server.md
          - maker-management-platform: applications/productivity/maker-management-platform.md
          - miniflux: applications/productivity/miniflux.md
          - nextexplorer: applications/productivity/nextexplorer.md
          - nocodb: applications/productivity/nocodb.md
          - outline: applications/productivity/outline.md
          - paperless: applications/productivity/paperless.md
          - paperless-gpt: applications/productivity/paperless-gpt.md
          - planka: applications/productivity/planka.md
          - plausible-analytics: applications/productivity/plausible-analytics.md
          - prerender: applications/productivity/prerender.md
          - psitransfer: applications/productivity/psitransfer.md
          - readeck: applications/productivity/readeck.md
          - readur: applications/productivity/readur.md
          - redirection: applications/productivity/redirection.md
          - sockpuppetbrowser: applications/productivity/sockpuppetbrowser.md
          - tandoor: applications/productivity/tandoor.md
      - Sandbox:
          - sandbox: applications/sandbox/sandbox.md
      - Security:
          - Overview: applications/security.md
          - cert-manager: applications/security/cert-manager.md
          - cert-manager-webhook-gandi: applications/security/cert-manager-webhook-gandi.md
          - external-secrets: applications/security/external-secrets.md
          - keycloak: applications/security/keycloak.md
          - kyverno: applications/security/kyverno.md
          - kyverno-cluster-policy: applications/security/kyverno-cluster-policy.md
          - sealed-secrets: applications/security/sealed-secrets.md
          - trivy-operator: applications/security/trivy-operator.md
          - vault: applications/security/vault.md
          - vault-sbx: applications/security/vault-sbx.md
      - Storage:
          - mongodb-operator: applications/storage/mongodb-operator.md
          - nfs-client: applications/storage/nfs-client.md
          - nfs-client-jonas: applications/storage/nfs-client-jonas.md
          - pg-prd: applications/storage/pg-prd.md
          - pg-sbx: applications/storage/pg-sbx.md
          - proxmox-csi: applications/storage/proxmox-csi.md

